[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
broadcast = "broadcast"

solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

gas_reports = ["*"]
auto_detect_solc = false

[profile.default.fuzz]
runs = 256

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = true

[rpc_endpoints]
arbitrum_one = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum_one = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
